spring.application.name=tungzone-payment-service
server.port=8084

spring.datasource.url=${DB_URL:jdbc:mysql://127.0.0.1:3306/tung_zone?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

app.jwt.secret=12345678901234567890123456789012
app.momo.partner-code=MOMOZRQO20260328_TEST
app.momo.access-key=NTG1yqAfz34daXAo
app.momo.secret-key=rf2JiHNSxgg3FpdkhsAITdmnJigaRQj9
app.momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
app.momo.ipn-url=http://localhost:8080/api/payments/momo/ipn
app.momo.redirect-url=http://localhost:5173/cart

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
