spring.application.name=tungzone-backend

# Laragon MySQL default config
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/tung_zone?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8080

app.jwt.secret=12345678901234567890123456789012
app.jwt.expiration=86400000
app.google.client-id=692763174418-3qskksrn30vadssdkgbu4gdim5bns98v.apps.googleusercontent.com

# MoMo IPN config
app.momo.partner-code=MOMOZRQO20260328_TEST
app.momo.access-key=NTG1yqAfz34daXAo
app.momo.secret-key=rf2JiHNSxgg3FpdkhsAITdmnJigaRQj9
app.momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
app.momo.ipn-url=https://playfully-semaphorical-collins.ngrok-free.dev/api/payments/momo/ipn
app.momo.redirect-url=http://localhost:5173/cart
app.upload.dir=uploads
